### ISSUE TITLE
Is there any way to remove the files on uninstall of the vsix?

### ISSUE THREAD

**Issue by mika76** [visualstudioextensibility/VSX-Samples#7]

**Comment by carlos-quintero** [comment]
Not really with this approach, since the package doesn't have the chance of running code when uninstalled, only when unloaded.

**Comment by mika76** [comment]
Too bad. Any other approaches available?

**Comment by carlos-quintero** [comment]
You can use MSI to deploy extensions, and MSI has the chance of executing code when uninstalled: https://blogs.msdn.microsoft.com/visualstudio/2009/10/26/vsix-and-msi/

**Comment by mika76** [comment]
Brilliant, thanks for the info.
